# Generated by Django 3.1.7 on 2021-09-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_compo'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compo',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glider',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tire',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compo',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.character'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='glider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.glider'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='tire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tire'),
        ),
        migrations.AlterField(
            model_name='compo',
            name='veh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehicle'),
        ),
        migrations.AlterField(
            model_name='glider',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='glider',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tire',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
